title: Hello, world! I'm Julio
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/Blog" # the subpath of your site, e.g. /blog
url: "https://flunkout-dvlpr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/flunkout_dvlpr #if your site has a twitter account, enter it here

# Author Settings
author: Julio C. Gonzalez # add your name
author-img: DEF92FE3-E462-4561-8BC9-3ACAF0E38C80.JPG # add your photo
about-author: flunkout to fullstack developer! # add description
social-twitter: flunkout_dvlpr # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: flunkout-dvlpr # add your Github handle
social-linkedin: julio-gonzalez-4b2904b0 # add your Linkedin handle
social-email: info@juliogonzalez.space # add your Email address

# Disqus
discus-identifier: flunkout-dvlpr # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji



paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
